# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: graphrag
services:
  app:
    image: graphrag
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_NEO4J_URI=bolt://neo4j:7687
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9099/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      neo4j:
        condition: service_healthy
  neo4j:
    extends:
      file: ./neo4j.yml
      service: neo4j
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
